### ISSUE TITLE
Rediriger weareleka.com et discovermoti.com vers leka.io

### ISSUE THREAD

**Issue by gsellator** [WeAreLeka/leka.io#2]
- Faire une redirection de type A vers l'ip de ton serveur azure pour weareleka.com et discovermoti.com
- Faire une redirection cname vers l'url de ton serveur azure pour www.weareleka.com et www.discovermoti.com

**Comment by ladislas** [comment]
dans un cas tu mets le `www` et dans l'autre non, c'est normal?

je fais donc type `A` pour les noms de domaines sans `www` et `CNAME` avec `www`?

Ou bien je fais `A` et `CNAME` pour `www` et sans `www`?

**Comment by gsellator** [comment]
La première possibilité 

--
Adrien Gsell

**Comment by ladislas** [comment]
c'est fait.
