### ISSUE TITLE
Répendre le nouveau picth de leka vers toutes les plateformes

### ISSUE THREAD

**Issue by gsellator** [WeAreLeka/leka.io#3]
"Leka is the first autonomous smart toy specifically designed for children with autism"

- mettre ce pitch sur
	-> fb
	-> twitter
	-> brandfolder
	-> youtube
	-> github

**Comment by ladislas** [comment]
on est pas encore sûr qu'on l'appelera Leka et pas un remplacement de Moti.

on peut pas plutôt garder Moti en attendant de trouver mieux?

**Comment by gsellator** [comment]
Je pense qu'il faut faire un choix toi de suite si tu veux bien ressortir sur Google dans 2 mois. Mais si tu choisis un autre nom, achete le nom de domaine qui va avec 

--
Adrien Gsell
