### ISSUE TITLE
Uniformiser le nom de la boîte et les urls sur toutes les plateformes

### ISSUE THREAD

**Issue by gsellator** [WeAreLeka/leka.io#4]
- [x] Fb et Twitter : Je te conseillerai volontiers de le mettre que Leka comme vrai nom sur (j'ai compris que le @leka n'était pas dispo dans les 2 cas, je parle sur nom affiché sur les pages). A toi de voir si ça te semble nécessaire.
- [x] Brandfolder : Changer le nom de compte 'moti' en 'leka' et changer l'adresse mail de contact en hello@leka.io
- [x] Github : Changer la homepage et l'adresse de contact

**Comment by ladislas** [comment]
sur fn j'ai fait la demande, ça prend 14j pour changer.

sur twitter, soit on garde weareleka soit on passe sur leka_io par exemple

**Comment by gsellator** [comment]
Ce message ne peut être affiché à cause de son format. Veuillez demander à l’expéditeur de le renvoyer en utilisant un autre format ou un autre logiciel de messagerie. text/html


--
Adrien Gsell

**Comment by ladislas** [comment]
j'arrive pas à avoir ta réponse, faut pas répondre dans gmail.

dis moi ce que tu penses pour twitter :)

**Comment by gsellator** [comment]
Le weareleka comme pseudo twitter et facebook me choque pas par contre je te suggérerais bien de ne mettre que Leka en "vrai nom"

**Comment by ladislas** [comment]
à l'aise je garde donc ce que j'ai en pseudo.

j'ai fait la demande fb qui prend 15jours et twitter c'est bon.
